---
title: "NAHPU Export Data Cleaning"
author: "Heru Handika"
date: "2023-06-16"
output: html_document
---

```{r}
if (!require("pacman")) {
  install.packages("pacman")
} 

pacman::p_load(readr)
pacman::p_load(dplyr)
pacman::p_load(here)
pacman::p_load(tidyr)

source(here::here("R", "lsumz_mammals", "data_cleaning.R"))
```


```{r}
path <- here::here("data", "hh_gede2023_specimenRecords.csv")

df <- readr::read_csv(path)
```

```{r}
matched.lsumz_cols <- c("specimenUUID", "genus", "species", "sex", "age", "country", "state", "county", "locality", "collectorLastName", "fieldNumber")

measurements.lsumz_cols <- c("totalLength", "tailLength", "hindFootLength", "earLength", "weight", "remarks")

coordinates.cols <- c("Latitude", "Longitude", "Elevation", "ElevationUnit", "MaxErrorDistance")

lsumz_cols <- c(matched.lsumz_cols, measurements.lsumz_cols)

prepType.size <- col_size(df$preparation)

prepType.colnames <- paste0("PrepType", 1:prepType.size)

coordinate.size <- col_size(df$coordinates)

coordinates.colnames <- paste0("Coordinate", 1:coordinate.size)

cleaned.df <-clean_collname(df) 

prepType.df <- prepType.colnames |>
  purrr::map(split_prepType) |>
  purrr::reduce(left_join, by = "specimenUUID")

coordinate.df <- coordinates.colnames |>
  purrr::map(split_coordinate) |>
  purrr::reduce(left_join, by = "specimenUUID") |>
  dplyr::select(specimenUUID, ends_with(".Coordinate1")) |>
  dplyr::rename_with(~stringr::str_remove(.x, pattern = ".Coordinate1")) |>
  dplyr::select(specimenUUID, all_of(coordinates.cols))

final.df <- cleaned.df |>
  dplyr::select(all_of(lsumz_cols)) |>
  dplyr::left_join(coordinate.df, by = "specimenUUID") |>
  dplyr::left_join(prepType.df, by = "specimenUUID") |>
  dplyr::relocate(all_of(coordinates.cols), .after = last_col()) |>
  dplyr::relocate(all_of(measurements.lsumz_cols), .after = last_col()) |>
  dplyr::select(-specimenUUID) 

readr::write_csv(final.df, here::here("results", "cleaned_lsumz_upload.csv"), na = "")
```

